/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoggleRouteImport } from './routes/boggle'
import { Route as ScribblerRouteImport } from './routes/scribbler'
import { Route as ScribblerJoinRouteImport } from './routes/scribbler.join'
import { Route as ScribblerNewRouteImport } from './routes/scribbler.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoggleRoute = BoggleRouteImport.update({
  id: '/boggle',
  path: '/boggle',
  getParentRoute: () => rootRouteImport,
} as any)
const ScribblerRoute = ScribblerRouteImport.update({
  id: '/scribbler',
  path: '/scribbler',
  getParentRoute: () => rootRouteImport,
} as any)
const ScribblerJoinRoute = ScribblerJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => ScribblerRoute,
} as any)
const ScribblerNewRoute = ScribblerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ScribblerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boggle': typeof BoggleRoute
  '/scribbler': typeof ScribblerRouteWithChildren
  '/scribbler/join': typeof ScribblerJoinRoute
  '/scribbler/new': typeof ScribblerNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boggle': typeof BoggleRoute
  '/scribbler': typeof ScribblerRouteWithChildren
  '/scribbler/join': typeof ScribblerJoinRoute
  '/scribbler/new': typeof ScribblerNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boggle': typeof BoggleRoute
  '/scribbler': typeof ScribblerRouteWithChildren
  '/scribbler/join': typeof ScribblerJoinRoute
  '/scribbler/new': typeof ScribblerNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/boggle' | '/scribbler' | '/scribbler/join' | '/scribbler/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/boggle' | '/scribbler' | '/scribbler/join' | '/scribbler/new'
  id:
    | '__root__'
    | '/'
    | '/boggle'
    | '/scribbler'
    | '/scribbler/join'
    | '/scribbler/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoggleRoute: typeof BoggleRoute
  ScribblerRoute: typeof ScribblerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boggle': {
      id: '/boggle'
      path: '/boggle'
      fullPath: '/boggle'
      preLoaderRoute: typeof BoggleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scribbler': {
      id: '/scribbler'
      path: '/scribbler'
      fullPath: '/scribbler'
      preLoaderRoute: typeof ScribblerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scribbler/join': {
      id: '/scribbler/join'
      path: '/join'
      fullPath: '/scribbler/join'
      preLoaderRoute: typeof ScribblerJoinRouteImport
      parentRoute: typeof ScribblerRoute
    }
    '/scribbler/new': {
      id: '/scribbler/new'
      path: '/new'
      fullPath: '/scribbler/new'
      preLoaderRoute: typeof ScribblerNewRouteImport
      parentRoute: typeof ScribblerRoute
    }
  }
}

interface ScribblerRouteChildren {
  ScribblerJoinRoute: typeof ScribblerJoinRoute
  ScribblerNewRoute: typeof ScribblerNewRoute
}

const ScribblerRouteChildren: ScribblerRouteChildren = {
  ScribblerJoinRoute: ScribblerJoinRoute,
  ScribblerNewRoute: ScribblerNewRoute,
}

const ScribblerRouteWithChildren = ScribblerRoute._addFileChildren(
  ScribblerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoggleRoute: BoggleRoute,
  ScribblerRoute: ScribblerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
